import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/system";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="w-screen bg-slate-900">
      <body className={`antialiased `}>
        <Header />
        {children}
      </body>
    </html>
  );
}
