import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";

import "../globals.css";
import { Header, SEO } from "@/components/system";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const messages = await getMessages();

  return (
    <html lang={locale} className="w-screen bg-slate-900">
      <body className={`antialiased`}>
        <NextIntlClientProvider messages={messages}>
          <SEO />
          <Header />
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
